"use strict";
exports.__esModule = true;
var linkedList_1 = require("./linkedList");
var list = new linkedList_1.List();
list.addFristNode('Tung', 8);
list.addFristNode('Tung', 5);
list.addFristNode('Tung', 2);
list.addFristNode('Phich', 9);
console.log(list.readList());
console.log(list.totalStudentsFail());
