export enum OptionNumber{
  OPTION_SHOWLISTSTUDENT_ = 1 ,
  OPTION_CREATESTUDENT_ = 2,
  OPTION_ADDSTUDENT_ = 3,
  OPTION_FINDSTUDENT_ = 4,
  OPTION_FINDGROUP_ = 5,
  OPTION_SORTBYAGE_ = 6,
  OPTION_EXIST_ = 0,
}