export let PRICEELECTRIC = 3000 ;
export enum Constant{
  OPTION_EXIST = 0 ,
  OPTION_RENDER_LIST_CUSTOMER = 1,
  OPTION_CREATE_CUSTOMER = 2,
  OPTION_DELETE_CUSTOMER = 3,
  OPTION_EDIT_CUSTOMER = 4,
  OPTION_PAY_BILL = 5,
  OPTION_UPDATE_AMOUNT_ELECTRIC = 6,

}
